### ISSUE TITLE
DATA DICTIONARY: Incorrect Use of Screenshot Instead of Markdown Table in Documentation

### ISSUE THREAD

**Issue by thirdygayares** [InventoryManagementSystemSVFC/InvetoryManagementSystem_Documentation#7]
The current documentation uses a screenshot to show a table. This makes it hard to update or change the content. Instead of using a screenshot, it's better to use a Markdown (MD) table. This will make it easier to update, track changes, and read on different devices.

Suggested Solution:
Replace the screenshot with a table in Markdown format. This will make it easy to edit and keep the table up to date.
Make sure the table matches the Entity Relationship Diagram (ERD) to keep everything in sync.

EXAMPLE

# Data Dictionary

## 1. Users Table

| Column Name     | Data Type     | Description                              | Constraints                                      |
|-----------------|---------------|------------------------------------------|--------------------------------------------------|
| user_id         | INT           | Unique identifier for the user.          | PRIMARY KEY, AUTO_INCREMENT                      |
| username        | VARCHAR(50)   | Username for login.                      | UNIQUE, NOT NULL                                 |
| password_hash   | VARCHAR(255)  | Hashed password for authentication.      | NOT NULL                                         |
| email           | VARCHAR(100)  | User's email address.                    | UNIQUE, NOT NULL                                 |
| phone_number    | VARCHAR(20)   | User's phone number.                     | NULLABLE                                         |
| first_name      | VARCHAR(50)   | User's first name.                       | NOT NULL                                         |
| last_name       | VARCHAR(50)   | User's last name.                        | NOT NULL                                         |
| user_role       | ENUM          | Role of the user (e.g., 'admin', 'user').| NOT NULL, DEFAULT 'user'                         |
| created_at      | DATETIME      | Timestamp of account creation.           | DEFAULT CURRENT_TIMESTAMP                        |
| updated_at      | DATETIME      | Timestamp of last account update.        | DEFAULT CUR

**Comment by bananacake2200** [comment]
okay po sir, noted po.
